---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: nginx
    ssd: "true"
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
        ssd: "true"
    spec:
      nodeSelector:
        ssd: "true"
      containers:
        - name: nginx
          image: nginx:1.10.0
