---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: kuard-data
      hostPath:
        path: "/var/lib/kuard"
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:1
      volumeMounts:
        - name: kuard-data
          mountPath: "/data"
      ports:
        - name: onlya1and-only
          containerPort: 8080
          protocol: TCP
